// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://inzyuclvvbgtjbfjonyvcpzyoy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-tzw3g6rjojej3jtpnciucw3fpu",
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:7ed6a901-3a5b-4d6e-bb51-cd62d270765f',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': '45133d3a36d84df2bc61a3605139598a',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '02b8617c-1b86-455c-b58a-dd470cc9ab4b',
    'aws_project_name': 'BugatchiMobile',
    'aws_resource_name_prefix': 'bugatchimobile-mobilehub-1051065218',
};

export default awsmobile;
